[book]
    authors = ["TrueBlocks, LLC"]
    language = "en"
    multilingual = false
    src = "src"
    title = "The Chifra Book"

[output.html]
    numbered = false
    default-theme = "rust"
    theme = "theme"

[preprocessor.mermaid]

